name: Build & Push Docker Images

on:
  push:
    branches:
      - main
      - master
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [backend, app]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/perplexica-${{ matrix.service == 'app' && 'frontend' || 'backend' }}

      - name: Extract version from release tag
        if: github.event_name == 'release'
        id: version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build and push Docker image for ${{ matrix.service }}
        if: github.ref_name == 'main' || github.ref_name == 'master'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ matrix.service == 'backend' && 'backend.dockerfile' || 'app.dockerfile' }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/perplexica-${{ matrix.service == 'app' && 'frontend' || 'backend' }}:latest
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/perplexica-${{ matrix.service == 'app' && 'frontend' || 'backend' }}:latest
          cache-to: type=inline

      - name: Build and push release Docker image
        if: github.event_name == 'release'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ matrix.service == 'backend' && 'backend.dockerfile' || 'app.dockerfile' }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/perplexica-${{ matrix.service == 'app' && 'frontend' || 'backend' }}:${{ env.RELEASE_VERSION }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/perplexica-${{ matrix.service == 'app' && 'frontend' || 'backend' }}:${{ env.RELEASE_VERSION }}
          cache-to: type=inline
